version: '3'

services:
  db:
    container_name: juniper-rocket-sample_postgres
    build: ./docker/postgresql/12-ja
    ports:
      - 15432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:
    driver: local
