[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.format]
command = "cargo"
args = ["fmt"]
install_crate = "rustfmt"

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.pre-commit]
dependencies = [
	"format",
	"test"
]

[tasks.db-migrate]
script = ['''
#!/bin/bash

diesel migration run
''']

[tasks.db-reset]
script = ['''
#!/bin/bash

diesel database reset

for filename in $(aws --endpoint-url $AWS_ENDPOINT_URL s3 ls s3://$BUCKET_NAME | tr -s ' ' | cut -d' ' -f4); do
  presigned_url=$(aws --endpoint-url $AWS_ENDPOINT_URL s3 presign "s3://$BUCKET_NAME/${filename}" --expires-in 604800)

  psql $DATABASE_URL --command "INSERT INTO videos (src) VALUES ('$presigned_url')"
done

psql $DATABASE_URL --command "SELECT * FROM videos;"
''']

[tasks.s3-reset]
script = ['''
#!/bin/bash

aws --endpoint-url $AWS_ENDPOINT_URL s3 rm s3://$BUCKET_NAME --recursive
aws --endpoint-url $AWS_ENDPOINT_URL s3 rb s3://$BUCKET_NAME
aws --endpoint-url $AWS_ENDPOINT_URL s3 mb s3://$BUCKET_NAME
aws --endpoint-url $AWS_ENDPOINT_URL s3 sync testdata/ s3://$BUCKET_NAME
''']
