[env]
PROFILE = "juniper-rocket-sample"

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.format]
command = "cargo"
args = ["fmt"]
install_crate = "rustfmt"

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.pre-commit]
dependencies = [
	"format",
	"test"
]

[tasks.db-migrate]
script = ['''
#!/bin/bash

diesel migration run
''']

[tasks.setup]
dependencies = [
	"reset-s3-testdata",
	"reset-db"
]

[tasks.reset-db]
script = ['''
#!/bin/bash

sleep 10

diesel database reset

for filename in $(aws --profile ${PROFILE} --endpoint-url ${AWS_ENDPOINT_URL} s3 ls s3://${BUCKET_NAME} | tr -s ' ' | cut -d' ' -f4); do
	psql ${DATABASE_URL} --command "INSERT INTO videos (src) VALUES ('${filename}')"
done

psql ${DATABASE_URL} --command "SELECT * FROM videos;"
''']

[tasks.reset-s3-testdata]
dependencies = ["configure-aws-credentials"]
script = ['''
#!/bin/bash

aws --profile ${PROFILE} --endpoint-url ${AWS_ENDPOINT_URL} s3 rm s3://${BUCKET_NAME} --recursive
aws --profile ${PROFILE} --endpoint-url ${AWS_ENDPOINT_URL} s3 rb s3://${BUCKET_NAME}
aws --profile ${PROFILE} --endpoint-url ${AWS_ENDPOINT_URL} s3 mb s3://${BUCKET_NAME}
aws --profile ${PROFILE} --endpoint-url ${AWS_ENDPOINT_URL} s3 sync testdata/ s3://${BUCKET_NAME}
''']

[tasks.configure-aws-credentials]
script = ['''
#!/bin/bash

aws configure --profile ${PROFILE} set aws_access_key_id ${AWS_ACCESS_KEY_ID}
aws configure --profile ${PROFILE} set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
''']
