[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.format]
command = "cargo"
args = ["fmt"]
install_crate = "rustfmt"

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.pre-commit]
dependencies = [
	"format",
	"test"
]

[tasks.db-migrate]
script = ['''
#!/bin/bash

diesel migration run
''']

[tasks.db-reset]
script = ['''
#!/bin/bash

docker-compose up &

sleep 10

diesel database reset

for filename in $(aws --profile minio --endpoint-url $AWS_ENDPOINT_URL s3 ls s3://$BUCKET_NAME | tr -s ' ' | cut -d' ' -f4); do
	src="$BUCKET_NAME/$filename"
	psql $DATABASE_URL --command "INSERT INTO videos (src) VALUES ('$src')"
done

psql $DATABASE_URL --command "SELECT * FROM videos;"

docker-compose stop

forego start
''']

[tasks.s3-reset]
script = ['''
#!/bin/bash

aws --endpoint-url $AWS_ENDPOINT_URL s3 rm s3://$BUCKET_NAME --recursive
aws --endpoint-url $AWS_ENDPOINT_URL s3 rb s3://$BUCKET_NAME
aws --endpoint-url $AWS_ENDPOINT_URL s3 mb s3://$BUCKET_NAME
aws --endpoint-url $AWS_ENDPOINT_URL s3 sync testdata/ s3://$BUCKET_NAME
''']
